image: ${XY_CODEHUB_REGISTRY_URL}/beachstudio/codehub/environment/runner/building/python/xy-pypi:latest

run:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_UPDATE_FLAGS: --jobs 4
    GIT_SUBMODULE_PATHS: xy_web_work/data/template/project xy_web_work/data/template/systemctl/config
  script:
    - echo "${CI_COMMIT_TAG}" > VERSION
    - python setup.py sdist
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  only:
    - tags
  tags:
    - xy-codehub
